"""Phase 1B migration: add the onboarding interview session table.

This is the single new process-data table for the conversational onboarding
flow. It stores the interview state machine (dimension coverage, progressive
understanding, question history, corrections). The final career profile is
still generated by F2 and stored in ``career_profile`` -- no other tables are
added in Phase 1B.

Idempotent: re-running this migration is a no-op if the table already exists.
"""
from __future__ import annotations

from sqlalchemy import inspect

from app.db.base import Base
from app import models  # noqa: F401 -- register CareerInterviewSession on metadata

VERSION = "0002"
NAME = "interview_session"

REQUIRED_TABLES = {"career_interview_session"}


def upgrade(eng):
    """Create the new table only (leave 0001 tables untouched)."""
    inspector = inspect(eng)
    existing = set(inspector.get_table_names())

    if "career_interview_session" in existing:
        return  # already applied (idempotent)

    # Create just the table(s) introduced by this migration. Using
    # Base.metadata.create_all with tables=[...] keeps it incremental and safe.
    Base.metadata.create_all(eng, tables=[Base.metadata.tables["career_interview_session"]])

    inspector = inspect(eng)
    existing = set(inspector.get_table_names())
    missing = REQUIRED_TABLES - existing
    if missing:
        raise RuntimeError(
            f"Migration {VERSION} failed: missing tables {sorted(missing)}"
        )
